18 Geopandas Connector : to sample from an existing database / sampling
IGNF/pacasam pull request #22
Opened 2023-06-21 15:26 UTC by CharlesGaydon

Avec CopySampler, on est en mesure de faire une copie de LiPaC a des fins de reproductibilités de jeux de donneés.
Avec GeopandasConnector, on peut sampler à partir de : 
1. Une copie faite par CopySampler
2. Un sampling. Cas d'usage : on a fait un premier sampling, et on veut observer si une réduction de taille peut avoir un bénéfice, en enlevant de la variabilité et en s'assurant que le bénéfice éventuel n'est pas lié aux aléa du sampling depuis LiPaC en entier.

Point d'attention 1 : CopySampler ou les autres sampling créent des colonnes "split" et "sampler" et on doit éviter des conflits éventuels avec les sampling suivants.
Point d'attention 2 : la variable connector_kwargs.split est utilisée pour nommer les gpkg de sortie. On part du principe qu'une colonne booléenne "test" est présentes dans les databases à échantillonner ; que si on utilise CopySampler il faut le faire avec spit=any pour tout garder ; et que avec GeopandasSampler on doit également préciser le split.

2023-06-21 16:48 UTC, CharlesGaydon commented
Principal problème de cette PR : le format de la configuration `configs/Synthetic_as_Geopackage.yml`. En effet actuellement on a besoin d'une configuration par connecteur. 
Pour moi la seule solution propre ce serait de passer par hydra (cf. https://github.com/IGNF/pacasam/issues/7) mais j'imagine faire ça plutôt dans une autre PR.

2023-06-22 14:53 UTC, leavauchier commented on src/pacasam/connectors/geopandas.py
> +        self.log = log
d'ailleurs je connaissais pas cette façon de faire en passant un logger d'objet en objet, J'arrive pas trop à me rendre compte de si il y aurait un moyen plus simple de passer la config du logger partout

2023-06-22 14:53 UTC, leavauchier commented on tests/tests_pacasam/test_run_sampling.py
> +    TWO_OUT_OF_FOUR = 2
Je comprends pas trop le nom de variable ici

2023-06-22 14:55 UTC, leavauchier commented on .vscode/launch.json
>              "args": [
j'ai l'impression que ce fichier-là ne devrait pas être dans le repo car il change en fonction de tes appels de fonction

2023-06-22 15:36 UTC, CharlesGaydon commented on src/pacasam/connectors/geopandas.py
> +        self.log = log
Oui bien vu, je corrige là et ailleurs.

Si tu trouve je veux bien, ce n'est pas pratique de devoir le trimballer. Là je passe un logger qui a été initialisé pour sauvegarder les logs dans un fichier texte. Je n'avais pas trouvé de façon de faire pour avoir un unique logger accessible partout mais qui _doit_ être initialisé dans p.ex. run_sampling..py (pour savoir dans quel dossier enregistrer les logs)...

Je sais qu'il y a le mot clef "global" mais je n'ai pas creusé l'idée 🤔

2023-06-22 15:38 UTC, CharlesGaydon commented on src/pacasam/connectors/synthetic.py
> +        log: Optional[logging.Logger],
fixed

2023-06-22 16:01 UTC, leavauchier requested changes

2023-06-22 16:01 UTC, leavauchier commented on src/pacasam/connectors/geopandas.py
> +        self.gpd_datab4ase_path = Path(gpd_database_path).resolve()
typo: `gpd_data4base_path` au lieu de  `gpd_database_path`

2023-06-22 16:04 UTC, leavauchier commented on src/pacasam/connectors/geopandas.py
> +        self.log = log
Je ne connais pas non plus le bon moyen pour faire ça, de mon côté c'est un point à creuser de façon générale

2023-06-22 16:05 UTC, leavauchier commented on .vscode/launch.json
>              "args": [
Issue créée pour garder ces infos, ça me parait pas mal comme décomposition

2023-06-26 09:59 UTC, CharlesGaydon commented
Conflits résolus. Il me reste une erreur sur test_main_graphs, que je ne parviens pas à reproduire en mode debug:
`FAILED tests/tests_pacasam/analysis/test_graphs.py::test_main_graphs - KeyError: 'split'`
Conflits résolus. Il me reste une erreur sur test_main_graphs, que je ne parviens pas à reproduire en mode debug (le test passe en mode debug avec `pytest -k test_main_graphs`).


Et dans le détail, quand je lance en ligne de commande "make tests", j'ai :
```

tests/tests_pacasam/analysis/test_graphs.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/pacasam/analysis/graphs.py:30: in main
    make_all_graphs_and_a_report(gpkg_path=args.gpkg_path, output_path=args.output_path)
src/pacasam/analysis/graphs.py:59: in make_all_graphs_and_a_report
    fig = viz_function(*viz_parameters)
src/pacasam/analysis/graphs.py:79: in make_class_histogram
    df_bool = df_bool.groupby(SPLIT_COLNAME)[nb_point_col_bool].sum().transpose()
/var/data/CGaydon/mambaforge/envs/pacasam/lib/python3.9/site-packages/pandas/core/frame.py:8262: in groupby
    return DataFrameGroupBy(
/var/data/CGaydon/mambaforge/envs/pacasam/lib/python3.9/site-packages/pandas/core/groupby/groupby.py:931: in __init__
tests/tests_pacasam/analysis/test_graphs.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/pacasam/analysis/graphs.py:30: in main
    make_all_graphs_and_a_report(gpkg_path=args.gpkg_path, output_path=args.output_path)
src/pacasam/analysis/graphs.py:59: in make_all_graphs_and_a_report
    fig = viz_function(*viz_parameters)
src/pacasam/analysis/graphs.py:79: in make_class_histogram
    df_bool = df_bool.groupby(SPLIT_COLNAME)[nb_point_col_bool].sum().transpose()
/var/data/CGaydon/mambaforge/envs/pacasam/lib/python3.9/site-packages/pandas/core/frame.py:8262: in groupby
    return DataFrameGroupBy(
/var/data/CGaydon/mambaforge/envs/pacasam/lib/python3.9/site-packages/pandas/core/groupby/groupby.py:931: in __init__



```

2023-06-26 14:50 UTC, leavauchier commented on src/pacasam/connectors/synthetic.py
> +    Each patch has the following types attributes :
typo:
```suggestion
    Each patch has the following types attributes:
```

2023-06-26 16:15 UTC, merged