OrthoimageExtractor
IGNF/pacasam pull request #47
Opened 2023-08-29 16:06 UTC by CharlesGaydon

Extracteur d'orthoimages RGB+NIR au format TIFF, à partir du géoportail.

2023-08-30 07:55 UTC, CharlesGaydon commented
TODO: 
- [ ] Merger https://github.com/IGNF/pacasam/pull/48 en premier
- [ ] Actualiser CHANGELOG et _version.py (0.9.0 ?)

2023-08-30 16:18 UTC, leavauchier requested changes
Question plus générale : pourquoi il te faut les orthoimages dans pacasam ? c'est pas sensé bosser sur du lidar ?

2023-08-30 16:18 UTC, leavauchier commented on README.md
> +- **Extractor**: créeent un jeu de données à prtir d'un sampling.
```suggestion
- **Extractor**: créeent un jeu de données à partir d'un sampling.
```

2023-08-30 16:18 UTC, leavauchier commented on README.md
> +- **Extractor**: créeent un jeu de données à prtir d'un sampling.
voire
```suggestion
- **Extractor**: création d'un jeu de données à partir d'un sampling.
``` 
pour être plus cohérent avec la suite

2023-08-31 13:58 UTC, CharlesGaydon commented on src/pacasam/extractors/orthoimages.py
> +        tmp_ortho = tempfile.NamedTemporaryFile(suffix=".tiff").name
Pris en compte ! Et en plus c'est plus élégant de ne pas créer les chemin temporaires dans la fonction elle-même.

J'ai fait de même pour collate_rgbnir_and_save pour être sûr que les fichiers sont bien fermés comme il faut par rasterio.

2023-08-31 14:04 UTC, CharlesGaydon commented on src/pacasam/extractors/extractor.py
> +        raise KeyError("Either SAMBA_USERNAME or SAMBA_PASSWORD were not exported, but you are using samba (USE_SAMBA is not null).")
Oui, je pense que maintenant les paramètres dans pyproject.toml sont bien pris en compte, alors qu'avant pacasam se faisait contaminer par des configs d'autres projets / de VS Code.
Quatre fichiers sont concernés, je ferai une passe sur main une fois cette MR mergée :)

2023-08-31 14:20 UTC, CharlesGaydon commented on src/pacasam/extractors/orthoimages.py
> +    proj = 2154
Oui tu as raison. J'ai rajouté la même méthode que pour `laz.py`, en permettant un contrôle du srid par patch via le sampling directement, et avec un défaut à 2154 tout de même.

2023-08-31 14:21 UTC, CharlesGaydon commented
> Question plus générale : pourquoi il te faut les orthoimages dans pacasam ? c'est pas sensé bosser sur du lidar ?

L'idée ici c'est d'utiliser le framework pacasam dans le cadre de la création d'un jeu de données "forêt" de classification. Je créée un jeu de nuages de points colorisés, mais également une version "images seules". :)

2023-08-31 14:32 UTC, leavauchier approved these changes

2023-08-31 15:04 UTC, merged