Remove samba and use a mounted store instead
IGNF/pacasam pull request #59
Opened 2023-10-26 15:33 UTC by CharlesGaydon

Le store sera sous /mnt/.

2023-10-31 13:30 UTC, leavauchier requested changes

2023-10-31 13:30 UTC, leavauchier commented on src/pacasam/connectors/lipac.py
> +    mounted_path = samba_path.replace("\\", "/").replace("//", "/").replace("store.ign.fr", "mnt")
je pense qu'il y a un moyen de faire ça de façon plus propre avec pathlib qui gère pas mal les chemins windows/linux
Peut-être avec quelque chose comme :
```python
relative_path = PureWindowsPath(samba_path).relative_to(PureWindowsPath("//store.ign.fr")
mounted_path = Path('/mnt') / relative_path
```

2023-10-31 13:32 UTC, leavauchier commented on src/pacasam/connectors/lipac.py
> +    mounted_path = samba_path.replace("\\", "/").replace("//", "/").replace("store.ign.fr", "mnt")
Je suis pas fan du `/mnt` en dur au milieu du code mais je sais pas trop où le mettre sinon

2023-11-02 11:35 UTC, CharlesGaydon commented on src/pacasam/connectors/lipac.py
> +    mounted_path = samba_path.replace("\\", "/").replace("//", "/").replace("store.ign.fr", "mnt")
Bonne idée pour pathlib.
En fait cette convention est spécifique au connecteur lidar donc je vais la lui assigner en méthode.

2023-11-02 12:44 UTC, leavauchier approved these changes

2023-11-02 16:08 UTC, merged