TargettedSampler now completes it selection to reach desired num of patches using the SpatialSampler
IGNF/pacasam pull request #70
Opened 2024-03-21 11:18 UTC by CharlesGaydon

2024-03-25 10:10 UTC, leavauchier requested changes

2024-03-25 10:10 UTC, leavauchier commented on src/pacasam/samplers/targetted.py
> +        elif self.complete_with_spatial_sampling:
est-ce que tu peux rajouter un test pour vérifier que tes 3 cas fonctionnent correctement ?

2024-04-02 13:21 UTC, CharlesGaydon commented
Added 2 tests. One required capturing a warning. I realized that log.warning != warning.warns. We need the latter if we want to capture a warning in pytest. Therefore I had to do a bit of refactoring of tests so that outputs of warning.warns are also logged by the logger.
I had to use the root logger (`logging.getLogger()` instead of `logging.getLogger(__name__)`) for this to happen.

2024-04-03 08:40 UTC, leavauchier approved these changes
J'ai une mini proposition d'amélioration mais c'est bon pour moi

2024-04-03 08:40 UTC, leavauchier commented on tests/tests_pacasam/samplers/test_targetted.py
> +    with pytest.warns(UserWarning, match="Selected more than the desired total"):
J'aurais pas pensé à aller récupérer le warning (juste récupérer la longueur de la sélection + comparer à la config me semblait suffire), mais bien vu !

2024-04-03 08:40 UTC, leavauchier commented on tests/tests_pacasam/samplers/test_targetted.py
> +    assert len(selection) < conf["target_total_num_patches"]
Suggestion : ajouter un test pour vérifier que la selection n'est pas vide (pour éviter un cas particulier)

2024-04-03 08:50 UTC, merged